using Microsoft.EntityFrameworkCore;
using ZvolenMenu.Api.Data;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("Default")));

builder.Services.AddControllers();
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
        policy.WithOrigins("http://localhost:5173")
            .AllowAnyHeader()
            .AllowAnyMethod());
});

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    // Ensure database exists and create EF model tables when possible
    await db.Database.EnsureCreatedAsync();

    // If some tables are missing (existing DB), create them individually
    await EnsureTablesExistAsync(db);

    await SeedData.EnsureSeededAsync(db);
}

// Local helper: check information_schema and create any missing tables/indexes
static async Task EnsureTablesExistAsync(ZvolenMenu.Api.Data.AppDbContext db)
{
    var required = new Dictionary<string, string>
    {
        ["Restaurants"] = @"CREATE TABLE IF NOT EXISTS ""Restaurants"" (
            ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" text NOT NULL,
            ""Address"" text NOT NULL,
            ""Latitude"" double precision NOT NULL,
            ""Longitude"" double precision NOT NULL,
            ""Phone"" text NULL,
            ""Website"" text NULL,
            CONSTRAINT ""PK_Restaurants"" PRIMARY KEY (""Id"")
        );",

        ["MenuTypes"] = @"CREATE TABLE IF NOT EXISTS ""MenuTypes"" (
            ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" text NOT NULL,
            CONSTRAINT ""PK_MenuTypes"" PRIMARY KEY (""Id"")
        );",

        ["DailyMenus"] = @"CREATE TABLE IF NOT EXISTS ""DailyMenus"" (
            ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            ""RestaurantId"" integer NOT NULL,
            ""MenuDate"" date NOT NULL,
            ""Note"" text NULL,
            CONSTRAINT ""PK_DailyMenus"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_DailyMenus_Restaurants_RestaurantId"" FOREIGN KEY (""RestaurantId"") REFERENCES ""Restaurants"" (""Id"") ON DELETE CASCADE
        );",

        ["Meals"] = @"CREATE TABLE IF NOT EXISTS ""Meals"" (
            ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            ""DailyMenuId"" integer NOT NULL,
            ""MenuTypeId"" integer NOT NULL,
            ""Name"" text NOT NULL,
            ""Description"" text NULL,
            ""Allergens"" text NULL,
            ""Price"" numeric(8,2) NOT NULL,
            ""SortOrder"" integer NOT NULL,
            CONSTRAINT ""PK_Meals"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_Meals_DailyMenus_DailyMenuId"" FOREIGN KEY (""DailyMenuId"") REFERENCES ""DailyMenus"" (""Id"") ON DELETE CASCADE,
            CONSTRAINT ""FK_Meals_MenuTypes_MenuTypeId"" FOREIGN KEY (""MenuTypeId"") REFERENCES ""MenuTypes"" (""Id"") ON DELETE RESTRICT
        );"
    };

    var indexSql = new[]
    {
        "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_DailyMenus_RestaurantId_MenuDate\" ON \"DailyMenus\" (\"RestaurantId\", \"MenuDate\");",
        "CREATE INDEX IF NOT EXISTS \"IX_Meals_DailyMenuId\" ON \"Meals\" (\"DailyMenuId\");",
        "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_MenuTypes_Name\" ON \"MenuTypes\" (\"Name\");"
    };

    var conn = db.Database.GetDbConnection();
    try
    {
        await conn.OpenAsync();
        foreach (var kv in required)
        {
            using var cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = @name;";
            var p = cmd.CreateParameter(); p.ParameterName = "@name"; p.Value = kv.Key; cmd.Parameters.Add(p);
            var exists = await cmd.ExecuteScalarAsync();
            if (exists is null)
            {
                using var create = conn.CreateCommand();
                create.CommandText = kv.Value;
                await create.ExecuteNonQueryAsync();
            }
        }

        foreach (var sql in indexSql)
        {
            using var c = conn.CreateCommand();
            c.CommandText = sql;
            await c.ExecuteNonQueryAsync();
        }
    }
    finally
    {
        await conn.CloseAsync();
    }
}

app.UseCors();
app.MapControllers();
app.Run();
